version: 0.2

env:
  variables:
    DOCKERHUB_USERNAME: "itsupport@aiocdawacs.com"
    DOCKERHUB_PASSWORD: "Limited@123"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - export DOCKERHUB_USERNAME=giftnature538@gmail.com
      - export DOCKERHUB_PASSWORD=Limited@123
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - echo Logging in to ECR...
      - export REPOSITORY_URI=390402542146.dkr.ecr.us-east-1.amazonaws.com/apache-1
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI 
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Generates a timestamp as a tag
      - docker info

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .  # Build the Docker image with the timestamp tag
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG  # Push the Docker image to ECR

artifacts:
  files: imagedefinitions.json
